version: '3'
services:
  ggr:
    restart: always
    image: aerokube/ggr
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "4444:4444"
    volumes:
      - "./etc/grid-router:/etc/grid-router:ro"
    command: ["-quotaDir", "/etc/grid-router/quota", "-listen", ":4444"]
  ggr-ui:
    network_mode: bridge
    restart: always
    image: aerokube/ggr-ui
    ports:
      - "8888:8888"
    volumes:
      - "./etc/grid-router:/etc/grid-router:ro"
  selenoid-ui:
    network_mode: bridge
    restart: always
    image: aerokube/selenoid-ui
    links:
      - ggr-ui
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://ggr-ui:8888"]
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "../selenoid/:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "../selenoid/video:/opt/selenoid/video"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/home/centos/selenoid/video
    command: ["-limit","10", "-service-startup-timeout","5m", "-session-attempt-timeout","5m", "-timeout","5m"]
    ports:
      - "4446:4444"